config {
  type: "view",
  name: "user_demographics"
}

WITH first_values AS (
    SELECT
        user_pseudo_id,
        geo.country as country,
        device.operating_system as operating_system,
        device.language as language,
        ROW_NUMBER() OVER (PARTITION BY user_pseudo_id ORDER BY event_timestamp DESC) AS row_num
    FROM ${ref("game_telemetry")}
    WHERE event_name="user_engagement"
    )
SELECT * EXCEPT (row_num)
FROM first_values
WHERE row_num = 1