apiVersion: v1
kind: Service
metadata:
  annotations:
    Service.kubernetes.io/topology-aware-hints: auto
  name: ml-serving-service-spend
  namespace: game-event-ns
  labels:
    app: ml-serving-spend
spec:
  selector:
    app: ml-serving-spend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-serving-spend
  namespace: game-event-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-serving-spend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ml-serving-spend
    spec:
      serviceAccountName: udp-k8s-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: ml-serving
          image: "${ARTIFACT_REPO_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/services-images/spend_serving:latest"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 2Gi
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - event-ingest
              topologyKey: "kubernetes.io/hostname"